# Data Acquisition Settings
# Comma-separated list of tickers to fetch (string)
# Provide as a single quoted string, separated by commas
# e.g., "AAPL,MSFT,GOOGL"
tickers: "AAPL,MSFT,NVDA" # Comma-separated list of tickers
# Date range for the data (YYYY-MM-DD)
start_date: "2024-01-01"   # Start date (YYYY-MM-DD)
end_date: "2024-03-01"     # End date (YYYY-MM-DD)
# Data interval
# Valid: 1m, 2m, 5m, 15m, 30m, 60m, 90m, 1h, 1d, 5d, 1wk, 1mo, 3mo
interval: "1d"             # Data interval (e.g., 1m, 5m, 1h, 1d, 1wk)
# Data source settings
data_source: "alphavantage"    # yfinance or alphavantage
api_key: "" # Only needed if data_source is alphavantage
# Column to use for calculations (for SMA and EMA)
column: "Close"

# Indicator Settings
# Comma-separated list: INDICATOR_NAME:param1-param2,OTHER_INDICATOR:param
# Example: "RSI:14,EMA:50,SMA:100,MACD:12-26-9,BBANDS:20-2,FIBO:0.236-0.382-0.5-0.618"
indicators: "MACD:12-26-9,FIBO:0.236-0.382-0.5-0.618,ADX:14,EMA:7,EMA:14"

# Plotting Options
plot_style: "candlestick" # line or candlestick
color_scheme: "tradingview" # default, monochrome, tradingview, dark
# up_color: "green"         # Optional: Custom up color
# down_color: "red"         # Optional: Custom down color
#interactive: true           # Enable interactive plot

# Multi-Plot Options (if applicable)
multi_plot: false          # Plot all tickers on the same plot
normalize: false           # Normalize data for multi-plot
log_scale: false           # Use logarithmic scale for multi-plot

# Saving Options
#save: True                 # Save the plot(s) to file automatically
#save_dir: "./plots_output" # Directory to save plots
#save_format: "png"         # Format: png, pdf, svg, jpg
#save_dpi: 300              # DPI for raster formats (png, jpg)